// appConfigFields.js
const appConfigFields = {
  NoOp: [
    {
      name: "label",
      label: "Label",
      type: "text",
      defaultValue: "Inbound Call from \\${CALLERID(num)} to \\${EXTEN}",
      helperText:
        "Label for the application. Use variables like \\${CALLERID(num)}, \\${EXTEN}",
    },
    {
      name: "logCallerInfo",
      label: "Log Caller Information",
      type: "checkbox",
      defaultValue: true,
      helperText: "Log caller number and destination for debugging",
    },
    {
      name: "logVariables",
      label: "Log Variables",
      type: "checkbox",
      defaultValue: false,
      helperText: "Log all channel variables for debugging",
    },
  ],
  Dial: [
    {
      name: "destination",
      label: "Destination Number",
      type: "text",
      defaultValue: "",
      required: true,
      helperText: "Enter the number to dial (e.g., SIP/1234 or PJSIP/1234)",
    },
    {
      name: "timeout",
      label: "Ring Timeout",
      type: "number",
      defaultValue: "30",
      required: true,
      helperText: "Ring timeout in seconds",
    },
    {
      name: "options",
      label: "Dial Options",
      type: "text",
      defaultValue: "tT",
      helperText: "Dial options (e.g., tT for transfer)",
    },
    {
      name: "callerId",
      label: "Caller ID",
      type: "text",
      defaultValue: "",
      helperText: "Optional: Override caller ID",
    },
    {
      name: "musicOnHold",
      label: "Music On Hold Class",
      type: "text",
      defaultValue: "default",
      helperText: "Music on hold class to use while dialing",
    },
    {
      name: "confirmCall",
      label: "Confirm Call",
      type: "checkbox",
      defaultValue: false,
      helperText: "Require called party to press 1 to accept the call",
    },
    {
      name: "recordCall",
      label: "Record Call",
      type: "checkbox",
      defaultValue: false,
      helperText: "Record the call after answer",
    },
  ],
  InternalDial: [
    {
      name: "internalExtension",
      label: "Internal Extension",
      type: "select",
      required: true,
      helperText: "Select an agent's extension",
      defaultValue: "",
    },
    {
      name: "timeout",
      label: "Timeout (seconds)",
      type: "number",
      required: false,
      helperText: "Ring timeout in seconds",
      defaultValue: "30",
    },
    {
      name: "url",
      label: "URL",
      type: "text",
      required: false,
      helperText: "URL to be called when the call is answered",
      defaultValue: "",
    },
    {
      name: "options",
      label: "Options",
      type: "text",
      required: false,
      helperText: "Additional options for the dial command",
      defaultValue: "xX",
    },
    {
      name: "enableRecording",
      label: "Enable Recording",
      type: "checkbox",
      required: false,
      helperText: "Enable call recording",
      defaultValue: false,
    },
    {
      name: "enableCallerId",
      label: "Enable Caller ID",
      type: "checkbox",
      required: false,
      helperText: "Enable caller ID",
      defaultValue: true,
    },
  ],
  ExternalDial: [
    {
      name: "number",
      label: "External Number",
      type: "text",
      defaultValue: "",
      required: true,
      helperText: "Enter the external phone number",
    },
    {
      name: "timeout",
      label: "Ring Timeout",
      type: "number",
      defaultValue: "30",
      required: true,
      helperText: "Ring timeout in seconds",
    },
    {
      name: "trunk",
      label: "Outbound Trunk",
      type: "select",
      options: [
        { value: "voip-provider", label: "VoIP Provider" },
        { value: "pstn", label: "PSTN" },
        { value: "sip-trunk", label: "SIP Trunk" },
      ],
      defaultValue: "voip-provider",
      required: true,
    },
  ],
  ringGroup: [
    {
      name: "user",
      label: "User",
      type: "select",
      options: [],
      defaultValue: "",
      required: true,
    },
    {
      name: "timeout",
      label: "Timeout",
      type: "number",
      defaultValue: 30,
    },
    {
      name: "options",
      label: "Options",
      type: "text",
      defaultValue: "xX",
    },
    {
      name: "url",
      label: "URL",
      type: "text",
      defaultValue: "",
    },
  ],
  Playback: [
    {
      name: "context",
      label: "Context",
      type: "text",
      defaultValue: "from-voip-provider",
      required: true,
      hidden: true,
    },
    {
      name: "exten",
      label: "Extension / Phone Number",
      type: "text",
      required: true,
      hidden: true,
    },
    {
      name: "priority",
      label: "Priority",
      type: "number",
      defaultValue: 13,
      required: true,
      helperText: "Dialplan priority for this application",
    },
    {
      name: "app",
      label: "Application",
      type: "text",
      defaultValue: "Playback",
      required: true,
      hidden: true,
    },
    {
      name: "answer",
      label: "Answer Call",
      type: "checkbox",
      defaultValue: true,
      required: true,
      helperText: "Answer the call before playing audio (recommended)",
    },
    {
      name: "audioFiles",
      label: "Audio Files",
      type: "select",
      // options: [],
      defaultValue: "",
      required: true,
      helperText: "Select audio file to play",
    },
    {
      name: "skipMs",
      label: "Skip (ms)",
      type: "number",
      defaultValue: 0,
      required: false,
      helperText: "Skip first N milliseconds of the audio",
    },
    {
      name: "noanswer",
      label: "No Answer",
      type: "checkbox",
      defaultValue: false,
      helperText: "Don't answer channel before playback",
    },
    {
      name: "synchronous",
      label: "Synchronous",
      type: "checkbox",
      defaultValue: true,
      helperText: "Wait for playback to complete before continuing",
    },
    {
      name: "channel",
      label: "Channel",
      type: "text",
      defaultValue: "",
      helperText: "Optional: Specific channel to play audio on",
    },
    {
      name: "type",
      label: "Type",
      type: "text",
      defaultValue: "inbound",
      required: true,
      hidden: true,
    },
    {
      name: "tag",
      label: "Tag",
      type: "text",
      defaultValue: "playback",
      required: true,
      hidden: true,
    },
  ],
  Queue: [
    {
      name: "queue",
      label: "Queue Name",
      type: "select",
      required: true,
      defaultValue: "",
      helperText: "Select a voice queue",
    },
    {
      name: "billingMode",
      label: "Billing Mode",
      type: "select",
      options: [
        { value: "tT", label: "Bill only when answered (tT)" },
        { value: "rn", label: "Bill immediately (rn)" },
        { value: "t", label: "Bill only when answered (t)" },
        { value: "T", label: "Bill only when answered (T)" },
        { value: "r", label: "Ring without billing (r)" },
        { value: "n", label: "No ring, no billing (n)" },
      ],
      defaultValue: "tT",
      required: true,
      helperText:
        "tT = Bill only when agent answers, rn = Bill immediately during ring",
    },
    {
      name: "timeout",
      label: "Timeout (seconds)",
      type: "number",
      defaultValue: 30,
      required: true,
      helperText: "How long to wait for an agent to answer",
    },
    {
      name: "preserveCallerId",
      label: "Preserve Caller ID",
      type: "checkbox",
      defaultValue: true,
      helperText: "Keep original caller ID for CDR tracking",
    },
    {
      name: "announceOverrides",
      label: "Announce Overrides",
      type: "select",
      options: [
        { value: "", label: "None" },
        { value: "agent_action_failure", label: "Agent Action Failure" },
        { value: "agent_end_pause", label: "Agent End Pause" },
        { value: "agent_login", label: "Agent Login" },
        { value: "agent_menu", label: "Agent Menu" },
        { value: "agent_pause", label: "Agent Pause" },
        { value: "call_rating_message", label: "Call Rating Message" },
        { value: "order_elaborated", label: "Order Elaborated" },
        { value: "order_message", label: "Order Message" },
        { value: "order_shipped", label: "Order Shipped" },
        { value: "thank_you", label: "Thank you" },
        { value: "welcome_message", label: "Welcome Message" },
      ],
      defaultValue: "",
    },
    {
      name: "url",
      label: "URL",
      type: "text",
      defaultValue: "",
      helperText: "Optional URL to call when call is answered",
    },
    {
      name: "agi",
      label: "AGI Script",
      type: "text",
      defaultValue: "",
      helperText: "Optional AGI script to execute",
    },
    {
      name: "macro",
      label: "Macro",
      type: "text",
      defaultValue: "",
      helperText: "Optional macro to execute",
    },
    {
      name: "goSub",
      label: "GoSub",
      type: "text",
      defaultValue: "",
      helperText: "Optional GoSub to execute",
    },
    {
      name: "rule",
      label: "Rule",
      type: "text",
      defaultValue: "",
      helperText: "Optional rule to apply",
    },
    {
      name: "position",
      label: "Position",
      type: "checkbox",
      defaultValue: false,
      helperText: "Add caller to specific position in queue",
    },
  ],
  Set: [
    {
      name: "variable",
      label: "Variable",
      type: "select",
      options: [
        { value: "CALLERID(num)", label: "CALLERID(num) - Caller Number" },
        { value: "CALLERID(name)", label: "CALLERID(name) - Caller Name" },
        { value: "CALLERID(dnid)", label: "CALLERID(dnid) - Dialed Number ID" },
        { value: "REAL_CALLER", label: "REAL_CALLER - Store Real Caller" },
        { value: "DESTINATION", label: "DESTINATION - Store Dialed Number" },
        { value: "CDR(userfield)", label: "CDR(userfield) - CDR User Field" },
        {
          value: "CDR(accountcode)",
          label: "CDR(accountcode) - CDR Account Code",
        },
        { value: "CDR(amaflags)", label: "CDR(amaflags) - CDR AMA Flags" },
        {
          value: "CDR(disposition)",
          label: "CDR(disposition) - CDR Disposition",
        },
        {
          value: "CDR(recordingfile)",
          label: "CDR(recordingfile) - CDR Recording File",
        },
        { value: "CDR(uniqueid)", label: "CDR(uniqueid) - CDR Unique ID" },
        { value: "CDR(src)", label: "CDR(src) - CDR Source" },
        { value: "CDR(dst)", label: "CDR(dst) - CDR Destination" },
        { value: "CDR(duration)", label: "CDR(duration) - CDR Duration" },
        { value: "CDR(billsec)", label: "CDR(billsec) - CDR Bill Seconds" },
        { value: "CDR(start)", label: "CDR(start) - CDR Start Time" },
        { value: "CDR(answer)", label: "CDR(answer) - CDR Answer Time" },
        { value: "CDR(end)", label: "CDR(end) - CDR End Time" },
        { value: "CHANNEL(language)", label: "CHANNEL(language)" },
        { value: "CHOICE", label: "CHOICE" },
        { value: "COUNTER", label: "COUNTER" },
        { value: "DBRESULT", label: "DBRESULT" },
        { value: "EMAIL", label: "EMAIL" },
        { value: "EXTRAVAR", label: "EXTRAVAR" },
        { value: "FIRSTNAME", label: "FIRSTNAME" },
        { value: "INPUT", label: "INPUT" },
        { value: "LASTNAME", label: "LASTNAME" },
        { value: "OPTION", label: "OPTION" },
        { value: "ORDER", label: "ORDER" },
        { value: "ORDERNUM", label: "ORDERNUM" },
        { value: "PHONE", label: "PHONE" },
        { value: "RATE", label: "RATE" },
        { value: "RESULT", label: "RESULT" },
        { value: "UNIQUEID", label: "UNIQUEID" },
        { value: "VAR1", label: "VAR1" },
        { value: "VAR2", label: "VAR2" },
        { value: "VAR3", label: "VAR3" },
        {
          value: "CALLED_NUMBER",
          label: "CALLED_NUMBER - Store Called Number",
        },
        { value: "CALLER_NAME", label: "CALLER_NAME - Store Caller Name" },
        { value: "CALL_QUALITY", label: "CALL_QUALITY - Store Call Quality" },
        {
          value: "TRANSFER_INFO",
          label: "TRANSFER_INFO - Store Transfer Information",
        },
        {
          value: "HOLD_DURATION",
          label: "HOLD_DURATION - Store Hold Duration",
        },
        {
          value: "RECORDING_PATH",
          label: "RECORDING_PATH - Store Recording Path",
        },
        {
          value: "CALL_TYPE",
          label: "CALL_TYPE - Store Call Type (inbound/outbound)",
        },
        { value: "CALL_STATUS", label: "CALL_STATUS - Store Call Status" },
        {
          value: "CALL_DURATION",
          label: "CALL_DURATION - Store Call Duration",
        },
        {
          value: "CALL_TIMESTAMP",
          label: "CALL_TIMESTAMP - Store Call Timestamp",
        },
        { value: "CALL_CODEC", label: "CALL_CODEC - Store Call Codec" },
        { value: "CALL_TRUNK", label: "CALL_TRUNK - Store Call Trunk" },
        { value: "CALL_CONTEXT", label: "CALL_CONTEXT - Store Call Context" },
        {
          value: "CALL_EXTENSION",
          label: "CALL_EXTENSION - Store Call Extension",
        },
        {
          value: "CALL_PRIORITY",
          label: "CALL_PRIORITY - Store Call Priority",
        },
        {
          value: "CALL_ANSWERED",
          label: "CALL_ANSWERED - Store Call Answered Status",
        },
        {
          value: "CALL_FAILED",
          label: "CALL_FAILED - Store Call Failed Status",
        },
        { value: "CALL_BUSY", label: "CALL_BUSY - Store Call Busy Status" },
        {
          value: "CALL_NO_ANSWER",
          label: "CALL_NO_ANSWER - Store Call No Answer Status",
        },
        {
          value: "CALL_REJECTED",
          label: "CALL_REJECTED - Store Call Rejected Status",
        },
        {
          value: "CALL_CANCELLED",
          label: "CALL_CANCELLED - Store Call Cancelled Status",
        },
        {
          value: "CALL_TRANSFERRED",
          label: "CALL_TRANSFERRED - Store Call Transferred Status",
        },
        {
          value: "CALL_FORWARDED",
          label: "CALL_FORWARDED - Store Call Forwarded Status",
        },
        {
          value: "CALL_PARKED",
          label: "CALL_PARKED - Store Call Parked Status",
        },
        {
          value: "CALL_PICKED_UP",
          label: "CALL_PICKED_UP - Store Call Picked Up Status",
        },
        {
          value: "CALL_QUEUED",
          label: "CALL_QUEUED - Store Call Queued Status",
        },
        {
          value: "CALL_DEQUEUED",
          label: "CALL_DEQUEUED - Store Call Dequeued Status",
        },
        { value: "CALL_AGENT", label: "CALL_AGENT - Store Call Agent" },
        { value: "CALL_QUEUE", label: "CALL_QUEUE - Store Call Queue" },
        { value: "CALL_IVR", label: "CALL_IVR - Store Call IVR" },
        {
          value: "CALL_VOICEMAIL",
          label: "CALL_VOICEMAIL - Store Call Voicemail",
        },
        {
          value: "CALL_RECORDING",
          label: "CALL_RECORDING - Store Call Recording",
        },
        {
          value: "CALL_MONITORING",
          label: "CALL_MONITORING - Store Call Monitoring",
        },
        { value: "CALL_WHISPER", label: "CALL_WHISPER - Store Call Whisper" },
        { value: "CALL_BARGE", label: "CALL_BARGE - Store Call Barge" },
        { value: "CALL_SPY", label: "CALL_SPY - Store Call Spy" },
        { value: "CALL_HOLD", label: "CALL_HOLD - Store Call Hold" },
        { value: "CALL_MUTE", label: "CALL_MUTE - Store Call Mute" },
        { value: "CALL_UNMUTE", label: "CALL_UNMUTE - Store Call Unmute" },
        { value: "CALL_UNHOLD", label: "CALL_UNHOLD - Store Call Unhold" },
        { value: "CALL_DTMF", label: "CALL_DTMF - Store Call DTMF" },
        { value: "CALL_TONE", label: "CALL_TONE - Store Call Tone" },
        { value: "CALL_MUSIC", label: "CALL_MUSIC - Store Call Music" },
        {
          value: "CALL_ANNOUNCEMENT",
          label: "CALL_ANNOUNCEMENT - Store Call Announcement",
        },
        { value: "CALL_MESSAGE", label: "CALL_MESSAGE - Store Call Message" },
        {
          value: "CALL_NOTIFICATION",
          label: "CALL_NOTIFICATION - Store Call Notification",
        },
        { value: "CALL_ALERT", label: "CALL_ALERT - Store Call Alert" },
        { value: "CALL_WARNING", label: "CALL_WARNING - Store Call Warning" },
        { value: "CALL_ERROR", label: "CALL_ERROR - Store Call Error" },
        { value: "CALL_DEBUG", label: "CALL_DEBUG - Store Call Debug" },
        { value: "CALL_LOG", label: "CALL_LOG - Store Call Log" },
        { value: "CALL_TRACE", label: "CALL_TRACE - Store Call Trace" },
        { value: "CALL_METRICS", label: "CALL_METRICS - Store Call Metrics" },
        {
          value: "CALL_ANALYTICS",
          label: "CALL_ANALYTICS - Store Call Analytics",
        },
        {
          value: "CALL_REPORTING",
          label: "CALL_REPORTING - Store Call Reporting",
        },
        { value: "CALL_BILLING", label: "CALL_BILLING - Store Call Billing" },
        { value: "CALL_RATING", label: "CALL_RATING - Store Call Rating" },
        {
          value: "CALL_FEEDBACK",
          label: "CALL_FEEDBACK - Store Call Feedback",
        },
        { value: "CALL_SURVEY", label: "CALL_SURVEY - Store Call Survey" },
        {
          value: "CALL_CUSTOMER",
          label: "CALL_CUSTOMER - Store Call Customer",
        },
        {
          value: "CALL_AGENT_ID",
          label: "CALL_AGENT_ID - Store Call Agent ID",
        },
        {
          value: "CALL_AGENT_NAME",
          label: "CALL_AGENT_NAME - Store Call Agent Name",
        },
        {
          value: "CALL_AGENT_EXTENSION",
          label: "CALL_AGENT_EXTENSION - Store Call Agent Extension",
        },
        {
          value: "CALL_AGENT_QUEUE",
          label: "CALL_AGENT_QUEUE - Store Call Agent Queue",
        },
        {
          value: "CALL_AGENT_STATUS",
          label: "CALL_AGENT_STATUS - Store Call Agent Status",
        },
        {
          value: "CALL_AGENT_PAUSE",
          label: "CALL_AGENT_PAUSE - Store Call Agent Pause",
        },
        {
          value: "CALL_AGENT_UNPAUSE",
          label: "CALL_AGENT_UNPAUSE - Store Call Agent Unpause",
        },
        {
          value: "CALL_AGENT_LOGIN",
          label: "CALL_AGENT_LOGIN - Store Call Agent Login",
        },
        {
          value: "CALL_AGENT_LOGOUT",
          label: "CALL_AGENT_LOGOUT - Store Call Agent Logout",
        },
        {
          value: "CALL_AGENT_BREAK",
          label: "CALL_AGENT_BREAK - Store Call Agent Break",
        },
        {
          value: "CALL_AGENT_AVAILABLE",
          label: "CALL_AGENT_AVAILABLE - Store Call Agent Available",
        },
        {
          value: "CALL_AGENT_BUSY",
          label: "CALL_AGENT_BUSY - Store Call Agent Busy",
        },
        {
          value: "CALL_AGENT_OFFLINE",
          label: "CALL_AGENT_OFFLINE - Store Call Agent Offline",
        },
        {
          value: "CALL_AGENT_ONLINE",
          label: "CALL_AGENT_ONLINE - Store Call Agent Online",
        },
        {
          value: "CALL_AGENT_IDLE",
          label: "CALL_AGENT_IDLE - Store Call Agent Idle",
        },
        {
          value: "CALL_AGENT_WRAP",
          label: "CALL_AGENT_WRAP - Store Call Agent Wrap",
        },
        {
          value: "CALL_AGENT_AFTER_CALL",
          label: "CALL_AGENT_AFTER_CALL - Store Call Agent After Call",
        },
        {
          value: "CALL_AGENT_PRE_CALL",
          label: "CALL_AGENT_PRE_CALL - Store Call Agent Pre Call",
        },
        {
          value: "CALL_AGENT_DURING_CALL",
          label: "CALL_AGENT_DURING_CALL - Store Call Agent During Call",
        },
        {
          value: "CALL_AGENT_POST_CALL",
          label: "CALL_AGENT_POST_CALL - Store Call Agent Post Call",
        },
        {
          value: "CALL_AGENT_PREPARATION",
          label: "CALL_AGENT_PREPARATION - Store Call Agent Preparation",
        },
        {
          value: "CALL_AGENT_COMPLETION",
          label: "CALL_AGENT_COMPLETION - Store Call Agent Completion",
        },
        {
          value: "CALL_AGENT_TRANSFER",
          label: "CALL_AGENT_TRANSFER - Store Call Agent Transfer",
        },
        {
          value: "CALL_AGENT_CONFERENCE",
          label: "CALL_AGENT_CONFERENCE - Store Call Agent Conference",
        },
        {
          value: "CALL_AGENT_HOLD",
          label: "CALL_AGENT_HOLD - Store Call Agent Hold",
        },
        {
          value: "CALL_AGENT_MUTE",
          label: "CALL_AGENT_MUTE - Store Call Agent Mute",
        },
        {
          value: "CALL_AGENT_UNMUTE",
          label: "CALL_AGENT_UNMUTE - Store Call Agent Unmute",
        },
        {
          value: "CALL_AGENT_UNHOLD",
          label: "CALL_AGENT_UNHOLD - Store Call Agent Unhold",
        },
        {
          value: "CALL_AGENT_DTMF",
          label: "CALL_AGENT_DTMF - Store Call Agent DTMF",
        },
        {
          value: "CALL_AGENT_TONE",
          label: "CALL_AGENT_TONE - Store Call Agent Tone",
        },
        {
          value: "CALL_AGENT_MUSIC",
          label: "CALL_AGENT_MUSIC - Store Call Agent Music",
        },
        {
          value: "CALL_AGENT_ANNOUNCEMENT",
          label: "CALL_AGENT_ANNOUNCEMENT - Store Call Agent Announcement",
        },
        {
          value: "CALL_AGENT_MESSAGE",
          label: "CALL_AGENT_MESSAGE - Store Call Agent Message",
        },
        {
          value: "CALL_AGENT_NOTIFICATION",
          label: "CALL_AGENT_NOTIFICATION - Store Call Agent Notification",
        },
        {
          value: "CALL_AGENT_ALERT",
          label: "CALL_AGENT_ALERT - Store Call Agent Alert",
        },
        {
          value: "CALL_AGENT_WARNING",
          label: "CALL_AGENT_WARNING - Store Call Agent Warning",
        },
        {
          value: "CALL_AGENT_ERROR",
          label: "CALL_AGENT_ERROR - Store Call Agent Error",
        },
        {
          value: "CALL_AGENT_DEBUG",
          label: "CALL_AGENT_DEBUG - Store Call Agent Debug",
        },
        {
          value: "CALL_AGENT_LOG",
          label: "CALL_AGENT_LOG - Store Call Agent Log",
        },
        {
          value: "CALL_AGENT_TRACE",
          label: "CALL_AGENT_TRACE - Store Call Agent Trace",
        },
        {
          value: "CALL_AGENT_METRICS",
          label: "CALL_AGENT_METRICS - Store Call Agent Metrics",
        },
        {
          value: "CALL_AGENT_ANALYTICS",
          label: "CALL_AGENT_ANALYTICS - Store Call Agent Analytics",
        },
        {
          value: "CALL_AGENT_REPORTING",
          label: "CALL_AGENT_REPORTING - Store Call Agent Reporting",
        },
        {
          value: "CALL_AGENT_BILLING",
          label: "CALL_AGENT_BILLING - Store Call Agent Billing",
        },
        {
          value: "CALL_AGENT_RATING",
          label: "CALL_AGENT_RATING - Store Call Agent Rating",
        },
        {
          value: "CALL_AGENT_FEEDBACK",
          label: "CALL_AGENT_FEEDBACK - Store Call Agent Feedback",
        },
        {
          value: "CALL_AGENT_SURVEY",
          label: "CALL_AGENT_SURVEY - Store Call Agent Survey",
        },
        {
          value: "CALL_AGENT_CUSTOMER",
          label: "CALL_AGENT_CUSTOMER - Store Call Agent Customer",
        },
      ],
      defaultValue: "CALLERID(num)",
      required: true,
      helperText: "Select the variable to set",
    },
    {
      name: "value",
      label: "Value",
      type: "text",
      defaultValue: "\\${CALLERID(num)}",
      required: true,
      helperText:
        "Enter the value or use variables like \\${CALLERID(num)}, \\${EXTEN}",
    },
    {
      name: "preserveOriginal",
      label: "Preserve Original",
      type: "checkbox",
      defaultValue: true,
      helperText: "Keep original value if new value is empty",
    },
  ],
  GoTo: [
    {
      name: "context",
      label: "Context",
      type: "select",
      options: [
        { value: "from-sip", label: "from-sip" },
        { value: "from-voip-provider", label: "from-voip-provider" },
        {
          value: "mayday-mixmonitor-context",
          label: "mayday-mixmonitor-context",
        },
      ],
      defaultValue: "from-sip",
    },
    {
      name: "extension",
      label: "Extension",
      type: "text",
      defaultValue: "",
      required: true,
    },
    {
      name: "priority",
      label: "Priority",
      type: "number",
      defaultValue: 1,
      required: true,
    },
  ],
  Hangup: [
    {
      name: "hangupCause",
      label: "Hangup Cause",
      type: "select",
      options: [
        { value: "1", label: "1 = Unallocated number" },
        { value: "16", label: "16 = Call Restricted" },
        { value: "17", label: "17 = User busy" },
        { value: "18", label: "18 = No user responding" },
        { value: "19", label: "19 = No answer" },
        { value: "21", label: "21 = Call rejected" },
        { value: "22", label: "22 = Number changed" },
        { value: "27", label: "27 = Destination out of order" },
        { value: "28", label: "28 = Invalid number format" },
        { value: "38", label: "38 = Network out of order" },
        { value: "41", label: "41 = Temporary failure" },
        { value: "42", label: "42 = Network congestion" },
        { value: "44", label: "44 = Requested channel not available" },
        { value: "58", label: "58 = Bearer capability not available" },
        { value: "65", label: "65 = Bearer capability not implemented" },
      ],
      defaultValue: "19", // Default to 'No answer'
      required: true,
    },
  ],
  SendDTMF: [
    {
      name: "dtmfDigits",
      label: "DTMF digits",
      type: "text",
      helperText:
        "Example 0123456789ABCDabcd*# w = pause 1/2 second, W = pause 1 second, f = flash hook",
      defaultValue: "",
      required: true,
    },
    {
      name: "timeoutBetweenTones",
      label: "Timeout between tones (ms)",
      type: "number",
      defaultValue: 25,
      validation: {
        min: 25,
      },
      required: true,
    },
    {
      name: "toneDuration",
      label: "Tone duration (ms)",
      type: "number",
      defaultValue: "",
      validation: {
        min: 25,
      },
      required: true,
    },
  ],
  Custom: [
    {
      name: "applicationName",
      label: "Application Name",
      type: "text",
      defaultValue: "",
      required: true,
    },
    {
      name: "arguments",
      label: "Arguments",
      type: "text",
      defaultValue: "",
    },
  ],
  IVR: [
    {
      name: "flowId",
      label: "IVR Flow",
      type: "select",
      required: true,
      helperText: "Select an IVR flow",
      defaultValue: "",
    },
  ],
};

export default appConfigFields;
