// Role-based permissions configuration
const PERMISSIONS = {
  // User management
  MANAGE_USERS: 'manage_users',
  VIEW_USERS: 'view_users',
  
  // Outlet management
  MANAGE_OUTLETS: 'manage_outlets',
  VIEW_OUTLETS: 'view_outlets',
  
  // Order management
  MANAGE_ORDERS: 'manage_orders',
  VIEW_ORDERS: 'view_orders',
  PROCESS_PAYMENTS: 'process_payments',
  
  // Reservation management
  MANAGE_RESERVATIONS: 'manage_reservations',
  VIEW_RESERVATIONS: 'view_reservations',
  
  // Inventory management
  MANAGE_INVENTORY: 'manage_inventory',
  VIEW_INVENTORY: 'view_inventory',
  
  // Menu management
  MANAGE_MENU: 'manage_menu',
  VIEW_MENU: 'view_menu',
  
  // Financial reports
  VIEW_FINANCIAL_REPORTS: 'view_financial_reports',
  MANAGE_FINANCIAL_REPORTS: 'manage_financial_reports',
  
  // Staff management
  MANAGE_STAFF: 'manage_staff',
  VIEW_STAFF: 'view_staff',
  MANAGE_SHIFTS: 'manage_shifts',
  
  // Guest management
  MANAGE_GUESTS: 'manage_guests',
  VIEW_GUESTS: 'view_guests',
  
  // Ticket management
  MANAGE_TICKETS: 'manage_tickets',
  VIEW_TICKETS: 'view_tickets',
  
  // Analytics and dashboard
  VIEW_ANALYTICS: 'view_analytics',
  VIEW_DASHBOARD: 'view_dashboard'
};

// Role permissions mapping
const ROLE_PERMISSIONS = {
  org_admin: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_OUTLETS,
    PERMISSIONS.VIEW_OUTLETS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.PROCESS_PAYMENTS,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.VIEW_MENU,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.MANAGE_SHIFTS,
    PERMISSIONS.MANAGE_GUESTS,
    PERMISSIONS.VIEW_GUESTS,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  general_manager: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_OUTLETS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.PROCESS_PAYMENTS,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.VIEW_MENU,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.MANAGE_SHIFTS,
    PERMISSIONS.MANAGE_GUESTS,
    PERMISSIONS.VIEW_GUESTS,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  supervisor: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.PROCESS_PAYMENTS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_MENU,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.VIEW_GUESTS,
    PERMISSIONS.MANAGE_GUESTS,
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  staff: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_MENU,
    PERMISSIONS.VIEW_GUESTS,
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  marketing_crm: [
    PERMISSIONS.VIEW_GUESTS,
    PERMISSIONS.MANAGE_GUESTS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  finance: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.PROCESS_PAYMENTS,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_DASHBOARD
  ]
};

export const getUserPermissions = (role) => {
  return ROLE_PERMISSIONS[role] || [];
};

export const hasPermission = (userRole, permission) => {
  const permissions = getUserPermissions(userRole);
  return permissions.includes(permission);
};

export { PERMISSIONS, ROLE_PERMISSIONS };
