module.exports = {
  apps: [
    {
      name: "hugamara-backend",
      script: "./backend/server.js",
      cwd: "/home/admin/hugamara-portal",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 5000,
        DB_HOST: "127.0.0.1",
        DB_PORT: 3306,
        DB_NAME: "hugamara_db",
        DB_USER: "hugamara_user",
        DB_PASSWORD: "Pasword@256",
        DB_SSL: "false",
      },
      error_file: "/home/admin/logs/hugamara-backend-error.log",
      out_file: "/home/admin/logs/hugamara-backend-out.log",
      log_file: "/home/admin/logs/hugamara-backend-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "mayday-callcenter-backend",
      script: "./mayday/slave-backend/server.js",
      cwd: "/home/admin/hugamara-portal",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
        DB_HOST: "127.0.0.1",
        DB_PORT: 3306,
        DB_NAME: "mayday_db",
        DB_USER: "mayday_user",
        DB_PASSWORD: "Mayday@256",
        DB_SSL: "false",
      },
      error_file: "/home/admin/logs/mayday-backend-error.log",
      out_file: "/home/admin/logs/mayday-backend-out.log",
      log_file: "/home/admin/logs/mayday-backend-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "mayday-callcenter-frontend",
      script: "serve",
      args: "-s ./mayday/mayday-client-dashboard/build -l 3001",
      cwd: "/home/admin/hugamara-portal",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      error_file: "/home/admin/logs/mayday-frontend-error.log",
      out_file: "/home/admin/logs/mayday-frontend-out.log",
      log_file: "/home/admin/logs/mayday-frontend-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
    },
  ],
};
